FROM ubuntu:xenial

ENV ARCH=x86_64
ENV DIST=ubuntu_xenial

SHELL ["/bin/bash", "-x", "-c"]

RUN apt-get update && \
    apt-get install -y build-essential wget curl patchelf vim-common fuse \
        libfuse2 libtool autoconf automake zlib1g-dev libjpeg-dev libpng-dev \
        nano git libssl-dev

# keep user ID in sync in and outside Docker image
ARG UID
RUN adduser --uid "$UID" --gecos "" build

USER build
CMD ["bash"]
