FROM arm32v7/ubuntu:focal

ENV ARCH=armhf DIST=ubuntu_focal

SHELL ["/bin/bash", "-x", "-c"]

RUN apt-get update && \
    apt-get install -y build-essential wget curl patchelf vim-common fuse \
        libfuse2 libtool autoconf automake zlib1g-dev libjpeg-dev libpng-dev \
        git libssl-dev

# keep user ID in sync in and outside Docker image
ARG UID
RUN adduser --uid "$UID" --gecos "" build

USER build
CMD ["bash"]
