name: Main pipeline

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  centos-7-x86_64:
    name: CentOS 7 (x86_64)
    env:
      DIST: centos7
      ARCH: x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build in Docker
        run: bash -ex build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CentOS 7 x86_64
          path: cmake*.tar*

  centos-7-i386:
    name: CentOS 7 (i386)
    env:
      DIST: centos7
      ARCH: i386
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build in Docker
        run: bash -ex build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CentOS 7 i386
          path: cmake*.tar*

  upload:
    name: Create release and upload artifacts
    needs:
      - centos-7-x86_64
      - centos-7-i386
    runs-on: ubuntu-18.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage **/cmake-v*.tar*
