name: Main pipeline

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  centos-7-x86_64:
    name: CentOS 7 (x86_64)
    env:
      DIST: centos7
      ARCH: x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build in Docker
        run: bash -ex build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CentOS 7 x86_64
          path: cmake*.tar*

  centos-7-i386:
    name: CentOS 7 (i386)
    env:
      DIST: centos7
      ARCH: i386
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build in Docker
        run: bash -ex build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CentOS 7 i386
          path: cmake*.tar*

  upload:
    name: Create release and upload artifacts
    needs:
      - centos-7-x86_64
      - centos-7-i386
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Extract version from tarball
        run: |
            VERSION="$(ls **/cmake-v*.tar* -1 | head -n1 | cut -d- -f2- | rev | cut -d- -f3- | rev)"
            echo -n "VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Create release and upload artifacts
        uses: marvinpinto/action-automatic-releases@latest
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${VERSION}"
          prerelease: false
          title: "${VERSION}"
          files: |
            **/cmake-v*.tar*
